/**:
  dvl_a50_node:
    ros__parameters:
      dvl_ip_address: "192.168.2.95"
      dvl_frame_id: bluerov2/dvl_link
      odom_frame_id: bluerov2/dvl_odom_ned
      startup_ntp_address: 192.168.2.103

  dvl_nav_interface:
    ros__parameters:
      odom_frame_id: bluerov2/dvl_odom         # The parent Frame ID used for the Odometry msg
      child_frame_id: bluerov2/base_link       # If the child frame id is the same as position_frame_id TF should not be published
      orientation_variance: 0.15
      publish_tf: false  # For the blueROV the imu will publish the transform 